//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepoUrun
    {
        public int ID { get; set; }
        public int UrunID { get; set; }
        public int DepoID { get; set; }
        public decimal Miktar { get; set; }
        public Nullable<decimal> BaslangicStok { get; set; }
        public int BirimID { get; set; }
    
        public virtual Depolar Depolar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
