//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class arabamis_MVC_StokTakipEntities : DbContext
    {
        public arabamis_MVC_StokTakipEntities()
            : base("name=arabamis_MVC_StokTakipEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Araclar> Araclar { get; set; }
        public virtual DbSet<AracMarka> AracMarka { get; set; }
        public virtual DbSet<Birimler> Birimler { get; set; }
        public virtual DbSet<Depolar> Depolar { get; set; }
        public virtual DbSet<DepoUrun> DepoUrun { get; set; }
        public virtual DbSet<Durumlar> Durumlar { get; set; }
        public virtual DbSet<Girisler> Girisler { get; set; }
        public virtual DbSet<Ýscilik> Ýscilik { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<KullaniciRolleri> KullaniciRolleri { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Satislar> Satislar { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<Servis> Servis { get; set; }
        public virtual DbSet<ServisKalem> ServisKalem { get; set; }
        public virtual DbSet<TamiratKalem> TamiratKalem { get; set; }
        public virtual DbSet<Tamiratlar> Tamiratlar { get; set; }
        public virtual DbSet<Tur> Tur { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
    }
}