//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Servis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servis()
        {
            this.ServisKalem = new HashSet<ServisKalem>();
        }

        public int ID { get; set; }
        public int DurumID { get; set; }
        public int AracID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime Tarih { get; set; }
        public Nullable<int> Km { get; set; }
        [AllowHtml]
        public string Not1 { get; set; }
        [AllowHtml]
        public string Not2 { get; set; }
        [AllowHtml]
        public string Not3 { get; set; }
        public decimal YToplam { get; set; }
        public decimal İToplam { get; set; }
        public decimal RotBalans { get; set; }
        public decimal MToplam { get; set; }
        public decimal Toplam { get; set; }
        public decimal İskonto { get; set; }
        public decimal GenelToplam { get; set; }

        public virtual Araclar Araclar { get; set; }
        public virtual Durumlar Durumlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisKalem> ServisKalem { get; set; }
    }
}
