//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServisKalem
    {
        public int ID { get; set; }
        public int ServisID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> TurID { get; set; }
        public Nullable<int> BirimID { get; set; }
        public decimal BirimFiyat { get; set; }
        public decimal Miktari { get; set; }
        public decimal ToplamTutar { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Tur Tur { get; set; }
        public virtual Servis Servis { get; set; }
    }
}
